services:
  node:
    build: .
    networks:
      - gcounter-net
    expose:
      - "7946"
    environment:
      - TOTAL_NODES=3 # Optional default, overridden at runtime
      - PEER_SERVICE=node
    deploy:
      mode: replicated
      replicas: 3  # Set replicas here instead of using --scale
    restart: unless-stopped

networks:
  gcounter-net:
    driver: bridge